#  conda env create --name bsseq --file environment.yaml 
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake=7.25.2
  - bowtie2=2.5.1
  - samtools=1.17
  - bismark=0.24.1
  - perl-gdgraph=1.54
  - ucsc-bedgraphtobigwig
  - deeptools=3.5.2
  - bedtools=2.31.0
